var1 = input("Enter your first number: ")
var2 = input ("Enter your second number: ")
sum = int(var1) + int(var2)
diff = int(var1) - int(var2)
prod = int(var1) * int(var2)
print("The sum of two variables is: ",sum)
print("The diff of two variables is: " ,diff)
print("The prod of two variables is: ",prod)
